export const POKEMONS_LOADING = "POKEMONS_LOADING";
export const POKEMONS_LOADED = "POKEMONS_LOADED";
export const SPECIFY_POKEMON_DETAILS = "SPECIFY_POKEMON_DETAILS";
export const ERASE_PREV_MAIN_STATE = "ERASE_PREV_MAIN_STATE";
export const SAVE_MAIN_PREV_STATE = "SAVE_MAIN_PREV_STATE";
